HW_5/HW_5/config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'
resources :sessions
resources :users

post '/login' => 'sessions#create'

post '/users' => 'users#create'

namespace :admin do

  resources :countries do
    resources :cities do
      resources :planes do
        resources :passengers do
          resources :tickets
        end
      end
    end
  end
end
end

HW_5/HW_5/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

end

HW_5/HW_5/app/models/city.rb
class City < ApplicationRecord
  belongs_to :country
  has_many :planes, dependent: :destroy
  validates_uniqueness_of :name, scope: :country_id, :presence => true
  validates :image, :presence => true, :uniqueness => { :allow_blank => true}
  has_attached_file :avatar, styles: { large:"600x600>", medium: "300x300>", thumb: "150x150#" }
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
end

HW_5/HW_5/app/models/country.rb
class Country < ApplicationRecord
  has_many :cities, dependent: :destroy
  validates :name, :presence => true, :uniqueness => { :allow_blank => true}
  validates :image, :presence => true, :uniqueness => { :allow_blank => true}
  has_attached_file :avatar, styles: { large:"600x600>", medium: "300x300>", thumb: "150x150#" }
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/, numericality: {allow_nill: true}

end

HW_5/HW_5/app/models/passenger.rb
class Passenger < ApplicationRecord
  belongs_to :plane
  has_many :tickets, dependent: :destroy
  validates_uniqueness_of :name, scope: :plane_id, :presence => true
  validates :image, :presence => true, :uniqueness => { :allow_blank => true}
  has_attached_file :avatar, styles: { large:"600x600>", medium: "300x300>", thumb: "150x150#" }
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
end

HW_5/HW_5/app/models/plane.rb
class Plane < ApplicationRecord
  belongs_to :city
  has_many :passengers, dependent: :destroy
  validates_uniqueness_of :name, scope: :city_id, :presence => true
  validates :image, :presence => true, :uniqueness => { :allow_blank => true}
  has_attached_file :avatar, styles: { large:"600x600>", medium: "300x300>", thumb: "150x150#" }
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
end

HW_5/HW_5/app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :passenger
  validates_uniqueness_of :name, scope: :passenger_id, :presence => true
  validates :image, :presence => true, :uniqueness => { :allow_blank => true}
  has_attached_file :avatar, styles: { large:"600x600>", medium: "300x300>", thumb: "150x150#" }
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
end

HW_5/HW_5/app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

HW_5/HW_5/app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
end

HW_5/HW_5/app/controllers/admin/cities_controller.rb
class Admin::CitiesController < Admin::BaseController

  def new
    @city = City.new(params[:id])
  end

  def create
    @country = Country.find(params[:country_id])
    @city = @country.cities.create(city_params)
    redirect_to admin_country_path(@country)
  end

  def show
    @country = Country.find(params[:country_id])

    # @city = City.find(params[:id])
    @city = Country.find(params[:country_id]).cities.find(params[:id])

  end

  private

  def city_params
    params.require(:city).permit(:name, :image, :country_id, :avatar)
  end
end

HW_5/HW_5/app/controllers/admin/countries_controller.rb
class Admin::CountriesController < Admin::BaseController
  def index
    @countries = Country.all
  end

  def show
    @country = Country.find(params[:id])
  end

  def new
    @country = Country.new
  end

  def create
    @country = Country.new(country_params)
    if @country.save
      redirect_to admin_countries_path
    else
      render :new
    end
  end

  def edit
    @country = Country.find(params[:id])
  end

  def update
    @country = Country.find(params[:id])
    if @country.update_attributes(country_params)
      redirect_to admin_countries_path
    else
      render :edit
    end
  end

  def destroy
    @country = Country.find(params[:id])
    @country.destroy()
    redirect_to admin_countries_path
  end

  private

def country_params
  params.require(:country).permit(:name, :image, :avatar)
end


end

HW_5/HW_5/app/controllers/admin/passengers_controller.rb
class Admin::PassengersController < Admin::BaseController

  def new
    @passenger = Passenger.new(params[:id])
  end

  def create
    @country = Country.find(params[:country_id])
    @city = City.find(params[:city_id])
    @plane = Plane.find(params[:plane_id])

    @passenger = @plane.passengers.create(passenger_params)

    redirect_to admin_country_city_plane_path(@country, @city, @plane)
  end

  def show
    @country = Country.find(params[:country_id])
    @city = City.find(params[:city_id])
    @plane = Plane.find(params[:plane_id])

    # @passenger = Passenger.find(params[:id])
    @passenger = Country.find(params[:country_id]).cities.find(params[:city_id]).planes.find(params[:plane_id]).passengers.find(params[:id])

  end

  private

  def passenger_params
    params.require(:passenger).permit(:name, :image, :country_id, :city_id, :plane_id, :avatar)
  end
end

HW_5/HW_5/app/controllers/admin/planes_controller.rb
class Admin::PlanesController < Admin::BaseController
  def new
    @plane = Plane.new(params[:id])
  end

  def create
    @country = Country.find(params[:country_id])
    @city = City.find(params[:city_id])
    @plane = @city.planes.create(plane_params)

    redirect_to admin_country_city_path(@country, @city)
  end

  def show
    @country = Country.find(params[:country_id])
    @city = City.find(params[:city_id])

    # @plane = Plane.find(params[:id])
    @plane = Country.find(params[:country_id]).cities.find(params[:city_id]).planes.find(params[:id])

  end

  private

  def plane_params
    params.require(:plane).permit(:name, :image, :country_id, :city_id, :avatar)
  end


end

HW_5/HW_5/app/controllers/admin/tickets_controller.rb
class Admin::TicketsController < Admin::BaseController
  def new
    @ticket = Ticket.new(params[:id])
  end

  def create
    @country = Country.find(params[:country_id])
    @city = City.find(params[:city_id])
    @plane = Plane.find(params[:plane_id])
    @passenger = Passenger.find(params[:passenger_id])


    @ticket = @passenger.tickets.create(ticket_params)

    redirect_to admin_country_city_plane_passenger_path(@country, @city, @plane, @passenger)
  end

  def show
    @country = Country.find(params[:country_id])
    @city = City.find(params[:city_id])
    @plane = Plane.find(params[:plane_id])
    @passenger = Passenger.find(params[:passenger_id])


    # @ticket = Ticket.find(params[:id])
    @ticket = Country.find(params[:country_id]).cities.find(params[:city_id]).planes.find(params[:plane_id]).passengers.find(params[:passenger_id]).tickets.find(params[:id])

  end

  private

  def ticket_params
    params.require(:ticket).permit(:name, :image, :country_id, :city_id, :plane_id, :passenger_id, :avatar)
  end
end

HW_5/HW_5/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
    redirect_to '/login' unless current_user
  end
end

HW_5/HW_5/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to admin_countries_path
    else
      redirect_to new_session_path

    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to new_session_path
  end

end

HW_5/HW_5/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
  end

  def create
    user = User.new(user_params)
    if user.save
      session[:user_id] = user.id
      redirect_to admin_countries_path
    else
      redirect_to new_user_path
    end
  end

private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

HW_5/HW_5/app/helpers/application_helper.rb
module ApplicationHelper
end

HW_5/HW_5/app/views/admin/cities/show.html.erb
<b><%= link_to "На главную", admin_countries_path%></b> | <%= link_to 'Назад', 'javascript:history.back()' %>

<h1> City = <%=  @city.name %></h1>
(<%= @city.image %>)

<p><%= image_tag @city.avatar.url(:thumb) %></p>


  <% @city.planes.each do |plane| %>
<p>___________________________________________________</p>
    <b>
      <h3>Plane = <%= link_to plane.name, admin_country_city_plane_path(@country, @city, plane) %></h3>
    </b>

    <p>
      <p>(<%= plane.image %>)</p>
    </p>

    <p><%= image_tag plane.avatar.url(:medium) %></p>



<% end %>


<p>--------------------------------------------------</p>
<h3>New Plane:</h3>
<%= form_with(model: [:admin, @country, @city, @city.planes.build ], local: true) do |f| %>
  <p>
    <%= f.label "Name(Plane)" %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label "Image(Plane)" %><br>
    <%= f.text_area :image %>
  </p>

  <p>
    <%= f.label :avatar %>
    <%= f.file_field :avatar %>
  </p>

  <p>
    <%= f.submit 'Save'%>

  </p>

<% end %>

HW_5/HW_5/app/views/admin/countries/_form.html.erb
<b><%= link_to "На главную", admin_countries_path %></b>
<%= form_for [:admin, @country], html: { multipart: true } do | f | %>

  <div class="form_control">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>


  <div class="form_control">
    <%= f.label :image %>
    <%= f.text_field :image %>
  </div>

  <div class="form_control">
    <%= f.label :avatar %>
    <%= f.file_field :avatar %>
  </div>

  <div class="form-control">
    <%= f.submit 'Save' %>
  </div>
<% end %>

HW_5/HW_5/app/views/admin/countries/edit.html.erb
<%= @country.name %>


<%= render 'form' %>

HW_5/HW_5/app/views/admin/countries/index.html.erb
<p><b><%= link_to 'Добавить страну', new_admin_country_path %></b></p>

<% @countries.each do | country | %>

<h1><%= link_to country.name, admin_country_path(country) %></h1>
<%= country.image %>

<p><%= image_tag country.avatar.url(:medium) %></p>
<p><%= link_to 'Изменить', edit_admin_country_path(country) %> |
  <%= link_to 'Удалить', admin_country_path(country), method: :delete, data: { confirm: 'Y/N?' } %></p>


  <% end %>

HW_5/HW_5/app/views/admin/countries/new.html.erb
<%= render 'form' %>

HW_5/HW_5/app/views/admin/countries/show.html.erb
<b><%= link_to "На главную", admin_countries_path%></b> | <%= link_to 'Назад', 'javascript:history.back()' %>

<h1> Country = <%=  @country.name %></h1>
(<%= @country.image %>)

<p><%= image_tag @country.avatar.url(:thumb) %></p>


  <% @country.cities.each do |city| %>
<p>___________________________________________________</p>
    <b>
      <h3>City = <%= link_to city.name, admin_country_city_path(@country, city) %></h3>
    </b>

    <p>
      <p>(<%= city.image %>)</p>
    </p>
    <p><%= link_to (image_tag city.avatar.url(:medium)), admin_country_city_path(@country, city) %></p>


<% end %>


<p>--------------------------------------------------</p>
<h3>New City:</h3>
<%= form_with(model: [ :admin, @country, @country.cities.build ], local: true) do |f| %>
  <p>
    <%= f.label "Name(City)" %><br>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label "Image(City)" %><br>
    <%= f.text_area :image %>
  </p>
  <p>
    <%= f.label :avatar %>
    <%= f.file_field :avatar %>
  </p>
  <p>
    <%= f.submit 'Save'%>

  </p>

<% end %>

HW_5/HW_5/app/views/admin/passengers/show.html.erb
<b><%= link_to "На главную", admin_countries_path%></b> | <%= link_to 'Назад', 'javascript:history.back()' %>
<h1>Passenger = <%= @passenger.name %></h1>
(<%= @passenger.image %>)
<p><%= image_tag @passenger.avatar.url(:thumb) %></p>

<% @passenger.tickets.each do |ticket| %>
<p>___________________________________________________</p>
  <b>
    <h3>Ticket = <%= link_to ticket.name, admin_country_city_plane_passenger_ticket_path(@country, @city, @plane, @passenger, ticket) %></h3>
  </b>

  <p>
    <p>(<%= ticket.image %>)</p>
  </p>
  <p><%= image_tag ticket.avatar.url(:medium) %></p>


<% end %>


<p>--------------------------------------------------</p>
<h3>New Ticket:</h3>
<%= form_with(model: [:admin, @country, @city, @plane, @passenger, @passenger.tickets.build ], local: true) do |f| %>
<p>
  <%= f.label "Name(Ticket)" %><br>
  <%= f.text_field :name %>
</p>
<p>
  <%= f.label "Image(Ticket)" %><br>
  <%= f.text_area :image %>
</p>
<p>
  <%= f.label :avatar %>
  <%= f.file_field :avatar %>
</p>
<p>
  <%= f.submit 'Save'%>

</p>

<% end %>

HW_5/HW_5/app/views/admin/tickets/show.html.erb
<b><%= link_to "На главную", admin_countries_path%></b> | <%= link_to 'Назад', 'javascript:history.back()' %>

<h1>Ticket = <%= @ticket.name %></h1>
(<%= @ticket.image %>)
<p><%= image_tag @ticket.avatar.url(:thumb) %></p>

HW_5/HW_5/app/views/users/new.html.erb
<h1>Регистрация</h1>

<%= form_for :user, url: '/users' do |f| %>

<p>Name: <%= f.text_field :name %>
Email: <%= f.text_field :email %></p>
<p>Password: <%= f.password_field :password %>
  Password Confirmation: <%= f.password_field :password_confirmation %>
  <p><%= f.submit "Регистрироватся" %></p></p>

<% end %>