HW_4/HW_4/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'stores#index'
  resources :stores do
    resources :categories do
      resources :products do
        resources :suppliers do
          resources :vendors

        end


      end

    end

  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

HW_4/HW_4/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

HW_4/HW_4/app/models/category.rb
class Category < ApplicationRecord
  belongs_to :store
  has_many :products, dependent: :destroy
  mount_uploader :avatar, AvatarUploader
  

end

HW_4/HW_4/app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  has_many :suppliers, dependent: :destroy
  mount_uploader :avatar, AvatarUploader
end

HW_4/HW_4/app/models/store.rb
class Store < ApplicationRecord
  has_many :categories, dependent: :destroy
  mount_uploader :avatar, AvatarUploader
end

HW_4/HW_4/app/models/supplier.rb
class Supplier < ApplicationRecord
  belongs_to :product
  has_many :vendors, dependent: :destroy
  mount_uploader :avatar, AvatarUploader
end

HW_4/HW_4/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

HW_4/HW_4/app/models/vendor.rb
class Vendor < ApplicationRecord
  belongs_to :supplier
  mount_uploader :avatar, AvatarUploader
end

HW_4/HW_4/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

HW_4/HW_4/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
before_action :authenticate_user!, except: [:index, :show]

    def new
      @category = Category.new(params[:id])
    end


  def create
    @store = Store.find(params[:store_id])
    @category = @store.categories.create(category_params)

    redirect_to store_path(@store)
  end


  def show
    @category = Category.find(params[:id])
    @store = Store.find(params[:store_id])
  end


  private

  def category_params
    params.require(:category).permit(:name, :image, :avatar)
  end
end

HW_4/HW_4/app/controllers/products_controller.rb
class ProductsController < ApplicationController
before_action :authenticate_user!, except: [:index, :show]
    def index
      @product = Product.all
    end

    def new
      @product = Product.new(params[:id])
    end


  def create
    @category = Category.find(params[:category_id])
    @store = Store.find(params[:store_id])
    @product = @category.products.create(product_params)

    redirect_to store_category_path(@store, @category)
  end


  def show
    @category = Category.find(params[:category_id])
    @store = Store.find(params[:store_id])
    @product = Product.find(params[:id])
  end


  private

  def product_params
    params.require(:product).permit(:name, :image, :store_id, :category_id, :avatar)
  end
end

HW_4/HW_4/app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  
  def index
    @stores = Store.all
  end

  def show
    @store = Store.find(params[:id])
  end

  def new
    @store = Store.new
  end

  def create
    @store = Store.new(store_params)
    if @store.save
      redirect_to stores_path
    else
      render :new
    end
  end

  def edit
    @store = Store.find(params[:id])
  end

  def update
    @store = Store.find(params[:id])
    if @store.update_attributes(store_params)
      redirect_to stores_path
    else
      render :edit
    end
  end
    def destroy
      @store = Store.find(params[:id])
      @store.destroy()
      redirect_to stores_path
    end

  private

  def store_params
    params.require(:store).permit(:name, :image, :avatar)
  end
end

HW_4/HW_4/app/controllers/suppliers_controller.rb
class SuppliersController < ApplicationController
before_action :authenticate_user!, except: [:index, :show]
    # def index
    #   @product = Product.all
    # end

    def new
      @supplier = Supplier.new(params[:id])
    end


  def create
    @store = Store.find(params[:store_id])
    @product = Product.find(params[:product_id])
    @category = Category.find(params[:category_id])
    @supplier = @product.suppliers.create(supplier_params)

    redirect_to store_category_product_path(@store, @category, @product)
  end


  def show
    @store = Store.find(params[:store_id])
    @product = Product.find(params[:product_id])
    @category = Category.find(params[:category_id])
    @supplier = Supplier.find(params[:id])
  end


  private

  def supplier_params
    params.require(:supplier).permit(:name, :image, :store_id, :category_id, :product_id, :avatar)
  end
end

HW_4/HW_4/app/controllers/vendors_controller.rb
class VendorsController < ApplicationController
before_action :authenticate_user!, except: [:index, :show]
    # def index
    #   @product = Product.all
    # end

    def new
      @vendor = Vendor.new(params[:id])
    end

def create
  @store = Store.find(params[:store_id])
  @category = Category.find(params[:category_id])
  @product = Product.find(params[:product_id])
  @supplier = Supplier.find(params[:supplier_id])

  @vendor = @supplier.vendors.create(vendor_params)
  redirect_to store_category_product_supplier_path(@store, @category, @product, @supplier)
end

def show
  @store = Store.find(params[:store_id])
  @product = Product.find(params[:product_id])
  @category = Category.find(params[:category_id])
  @supplier = Supplier.find(params[:supplier_id])

  @vendor = Vendor.find(params[:id])
end


  private

  def vendor_params
    params.require(:vendor).permit(:name, :image, :store_id, :category_id, :product_id, :supplier_id, :avatar)
  end
end

HW_4/HW_4/app/views/categories/show.html.erb
<%= link_to 'Back', 'javascript:history.back()' %>
<h1><%= @category.name %><h1>

<h3>(<%= @category.image %>)</h3>


    <% @category.products.each do |product| %>
    <h2>Products</h2>

      <b>
        <h2> <%= link_to product.name, store_category_product_path(@store, @category, product)  %></h2>
      </b>

      <p>
        <h3><%= product.image %></h3>
      </p>
      <% if product.avatar.url %>
      <%= image_tag product.avatar.url(:thumb) %>
      <% else %>

      <% end %>

  <p>--------------------------------------------------</p>
  <% end %>



  <h2>New Product:</h2>
  <%= form_with(model: [@store, @category, @category.products.build ], local: true, html: {multipart: true}) do |f| %>
    <p>
      <%= f.label "Name(Product)" %><br>
      <%= f.text_field :name %>
    </p>
    <p>
      <%= f.label "Image(Product)" %><br>
      <%= f.text_area :image %>
    </p>
    <div class="form-group">
      <%= f.file_field :avatar %>
    </div>


    <p>
      <%= f.submit 'Save'%>

    </p>

  <% end %>

HW_4/HW_4/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hw4</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <% if user_signed_in? %>
  <%= link_to "Выход", destroy_user_session_path, method: :delete %>
  <% else %>
  <%= link_to "Вход", new_user_session_path%>
  |<%= link_to "Регистрация", new_user_registration_path%>
<% end %>
  <body>

    |<%= link_to 'Главная', stores_path %>

    <%= yield %>
    <p><%= "тестовый логин - t1@t1.ck" %></p>
    <p><%= "тестовый пароль - 123456789"%></p>
  </body>
</html>

HW_4/HW_4/app/views/stores/_form.html.erb
<%= form_for @store, html: {multipart: true} do |f| %>

<div class="form-control">
  <%= f.label :name %>
  <%= f.text_field :name %>
</div>

<div class="form-control">
  <%= f.label :image %>
  <%= f.text_area :image %>
</div>

<div class="form-group">
  <%= f.file_field :avatar %>
</div>

<div class="form-control">
  <%= f.submit 'Сохранить' %>
</div>

<% end %>

HW_4/HW_4/app/views/stores/edit.html.erb
<%= @store.name %>


<%= render 'form' %>

HW_4/HW_4/app/views/stores/index.html.erb
    |  <b><%= link_to 'Новая статья', new_store_path %></b>
<% @stores.each do |store| %>

<h1>  <%= link_to store.name, store_path(store) %></h1>
<b> ( <%= store.image %></b> )

<p>   <%= link_to 'Изменить', edit_store_path(store) %>
<%= link_to 'Удалить', store_path(store), method: :delete, data: { confirm: 'Y/N?' } %></p>

<% if store.avatar.url %>
<%= image_tag store.avatar.url(:thumb) %>
<% else %>

<% end %>


<p>__________________________________________________________</p>

 <% end %>
 <p><%="Незарегистрированы пользователи могут только просматривать."%></p>

HW_4/HW_4/app/views/stores/new.html.erb
<%= render 'form' %>

HW_4/HW_4/app/views/stores/show.html.erb
<%= link_to 'Back', 'javascript:history.back()' %>
<h1><%= @store.name %><h1> <h3>(<%= @store.image %>)</h3>





  <% @store.categories.each do |category| %>

    <b>
      <h2>Categorise = <%= link_to category.name, store_category_path(@store, category) %></h2>
    </b>

    <p>
      <h2>Image = (<%= category.image %>)</h2>
    </p>
    <% if category.avatar.url %>
    <%= image_tag category.avatar.url(:thumb) %>
    <% else %>

    <% end %>

<p>--------------------------------------------------</p>
<% end %>



<h2>New Categories:</h2>
<%= form_with(model: [ @store, @store.categories.build ], local: true, html: {multipart: true}) do |f| %>
  <p>
    <%= f.label "Name(Category)" %><br>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label "Image(Category)" %><br>
    <%= f.text_area :image %>
  </p>

  <div class="form-group">
    <%= f.file_field :avatar %>
  </div>


  <p>
    <%= f.submit 'Save'%>

  </p>

<% end %>

HW_4/HW_4/app/views/vendors/show.html.erb
<%= link_to 'Back', 'javascript:history.back()' %>
<h1><%= @vendor.name %><h1>

<h2><%= @vendor.image %><h2>